src/dashboard/urls.py
from django.urls import  path
from dashboard.views import index

app_name= "dashboard"
urlpatterns = [
   path('', index, name='index'),
]
 

src/report/urls.py
from django.urls import  path
from . import views

app_name="report"
urlpatterns = [
   path('', views.index, name="index"),
]

src/student/urls.py
from django.urls import  path
from . import views

app_name= "student"
urlpatterns = [
   path('', views.index, name="index"),
   path('ajouterStudent', views.ajoutStudent, name="ajouterStudent" ),  
   path('modifierStudent/<int:id>/', views.modifierStudent, name="modifierStudent" ),
   path('suprimer/<int:id>', views.suprimer, name ='suprimer' ),
   
]

src/teacher/urls.py
from django.urls import  path
from . import views

app_name="teacher"
urlpatterns = [
   path('', views.index, name="index"),
   path('ajouterTeacher/', views.ajouterTeacher, name='ajouterTeacher' ),
   path('modifierTeacher/<int:id>/', views.modifierTeacher, name='modifierTeacher' ),
   path('suprimer/<int:id>', views.suprimer, name ='suprimer' ),
   
]

src/user/urls.py
from django.urls import  path
from . import views

app_name="user"
urlpatterns = [
   path('', views.index, name="index"),
   path('ajouterUser/', views.ajouterUser, name ='ajouterUser' ),
   path('modifierUser/<int:id>/', views.modifierUser, name='modifierUser' ),
   path('suprimer/<int:id>/', views.suprimer, name ='suprimer' ),

]

src/website/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include('student.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('teacher/',include('teacher.urls')),
    path('user/',include('user.urls')),
    path('report/',include('report.urls')),
]

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <!--  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="sidebar">
        <img src="image.avif" alt="Logo de l'Établissement">
        <h2>Menu</h2>
        <ul>
            <li><a href="{% url 'dashboard:index' %}">Dashboard</a></li>
            <li><a href="{% url 'student:index' %}">Élèves</a></li>
            <li><a href="{% url 'teacher:index' %}">Professeurs</a></li>
            <li><a href="{% url 'user:index' %}">Utilisateurs</a></li>
            <li><a href="{% url 'report:index' %}">Rapports</a></li>
        <div class="logout-button" onclick="logout()">Se déconnecter</div>

        </ul>
    </div>

    <div class="main-content">
        {% block content %}
        {% endblock content %}
    </div>

    
    
</body>

</html>