src/dashboard/urls.py
from django.urls import  path
from dashboard.views import index

app_name= "dashboard"
urlpatterns = [
   path('', index, name='index'),
]
 

src/teacher/urls.py
from django.urls import  path
from . import views

app_name="teacher"
urlpatterns = [
   path('', views.index, name="index"),
   path('ajouterTeacher/', views.ajouterTeacher, name='ajouterTeacher' ),
   path('modifierTeacher/<int:id>/', views.modifierTeacher, name='modifierTeacher' ),
   path('suprimer/<int:id>', views.suprimer, name ='suprimer' ),
   
]

src/user/urls.py
from django.urls import  path
from . import views

app_name="user"
urlpatterns = [
   path('', views.index, name="index"),
   path('ajouterUser/', views.ajouterUser, name ='ajouterUser' ),
   path('modifierUser/<int:id>/', views.modifierUser, name='modifierUser' ),
   path('suprimer/<int:id>/', views.suprimer, name ='suprimer' ),

]

src/website/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include('student.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('teacher/',include('teacher.urls')),
    path('user/',include('user.urls')),
    path('report/',include('report.urls')),
]

src/teacher/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=30)
    #birth_date = models.DateField()
    city = models.CharField(max_length=30)
    number = models.CharField(max_length=10)
    vacation = models.BooleanField()
    subject_taught = models.CharField(max_length=30)
    next_course = models.CharField(max_length=30)
    subject_next_meet = models.CharField(max_length=30)

src/teacher/forms.py
from django import forms
from .models import Teacher

class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields=["first_name","last_name","city","number","vacation","subject_taught","next_course","subject_next_meet"]

src/teacher/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .forms import TeacherForm
from .models import Teacher
# Create your views here.
def index(request):
    teachers = Teacher.objects.all()
    context = { 'teachers': teachers }
    
    return render(request,'teacher/indexTeacher.html',context)

def ajouterTeacher(request):
    
    if request.method == "POST":
        print(request.POST)
        form = TeacherForm(request.POST)
        
        if form.is_valid():
           print(form.cleaned_data)
           form.save()
           return redirect('teacher:index')
        else:
            return render(request, 'teacher:modifierTeacher', context)  
    form = TeacherForm()
    context = {'form': form}
    return render(request, 'teacher/ajouterTeacher.html', context)

def modifierTeacher(request,id):
    teacher = Teacher.objects.get(id=id)
    context = {'title':'modification teacher'}
    
    if request.method == 'POST':
        form = TeacherForm(request.POST , instance = teacher)
        if form.is_valid():
            form.save()
            return redirect('teacher:index')
    
    form = TeacherForm(instance = teacher)
    context = {'form': form}
    return render(request, 'teacher/modifierTeacher.html', context)   

def suprimer (request, id):
    teacher = Teacher.objects.get(id = id)
    teacher.delete()
    return redirect('teacher:index')

src/templates/teacher/ajouterTeacher.html
{% extends 'base.html' %}
{%  load static %}
{% block content %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un Professeur</title>
    
    <link rel="stylesheet" href="{% static 'css/styleAjout.css'   %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.6.0/css/bootstrap.min.css" rel="stylesheet">
    <a href="{% url 'teacher:index' %}">
        <button>Retour</button>
    </a>
</head>
<body>
    

    <div class="main-content">
        <header>
            <h1>Ajouter Professeurs</h1>
        </header>

        <div class="form-container">
            <h2>Formulaire d'ajout professeurs</h2>
            <form id="add-prof-form" action="" method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <br><br>

                <div class="form-actions">
                    <button type="submit" class="save-button">Enregistrer</button>
                    <button type="reset" class="cancel-button" onclick="cancel()">Annuler</button>
                </div>
                
            </form>
        </div>
    </div>

   
    {% endblock content %}

src/templates/teacher/indexTeacher.html
{% extends 'base.html' %}

{% block content %}

<header>
    {% block contenu %}
    <title>Liste des Professeurs</title>
    {% endblock contenu %}
    <h1>Liste des Professeurs</h1>
    <a href="{% url 'teacher:ajouterTeacher' %}">
        <button class="add-button">Nouveau professeur</button>
    </a>
</header>
<a href="{% url 'dashboard:index' %}">
    <button>Retour</button>
</a>
<table>
    <thead>
        <tr>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Ville</th>
            <th>Telephone</th>
            <th>Vacant</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for teacher in teachers %}
            <tr id="prof-1">
                <td> {{ teacher.first_name }} </td>
                <td> {{ teacher.last_name }} </td>
                <td> {{ teacher.city }} </td>
                <td> {{ teacher.number }} </td>
                <td> {{ teacher.vacation }} </td>
                <td class="action-buttons">
                    <a href="{% url 'teacher:modifierTeacher' teacher.id %}">
                        <button class="edit-button">Update</button>
                    </a>
                    <a href="{% url 'teacher:suprimer' teacher.id %}">
                        <button class="edit-button" onclick="confirmDelete(1)">Remove</button>
                    </a>   
                </td>
            </tr>
        {% endfor %}

        <script>
            function logout() {
                // Implémentez la logique de déconnexion ici
                alert('Déconnexion effectuée !');
            }
    
            function confirmDelete(id) {
                const confirmation = confirm('Êtes-vous sûr de vouloir supprimer ?');
                if (confirmation) {
                    // Si l'utilisateur confirme la suppression
                    alert('Professeur avec ID ' + id + ' supprimé.');
                    
                    // Suppression de la ligne du tableau correspondante
                    const row = document.getElementById('prof-' + id);
                    row.remove();
                }
            }
        </script>
    
    </tbody>
</table>

{% endblock content %}

src/templates/teacher/modifierTeacher.html
{% extends 'base.html' %}
{% block content %}
{% load static%}


<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier un Professeur</title>
   <link rel="stylesheet" href="{% static 'css/styleModif' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.6.0/css/bootstrap.min.css" rel="stylesheet">

</head>


    <div class="main-content">
        <header>
            <h1>Modifier Professeurs</h1>
            <a href="{% url 'teacher:index' %}">
                <button>Retour</button>
            </a>
        </header>
        

        <div class="form-container">
            <h2>Formulaire de modification professeurs</h2>
            <form id="add-prof-form" method="post">
                {{ form }}
                {% csrf_token %}
                <br><br>

                <div class="form-actions">
                    <button type="submit" class="save-button">Enregistrer</button>
                    <button type="button" class="cancel-button" onclick="cancel()">Annuler</button>
                </div>
               
               
                <div class="form-message" id="form-message"></div> 
            </form>
        </div>
    </div>

   
    {% endblock content %}